const config = require('../../config.json');
const mongoose = require('mongoose');

const guildSchema = new mongoose.Schema({
	guildID: String,
	lastEdited: String,
	prefix: { type: String, default: config.prefix },
	memberRoleID: { type: String, required: false },
	welcomeChannel: { type: String },
	levelupChannel: { type: String },
	ticketChannel: { type: String },
	ticketCategory: { type: String },
	transcriptChannel: { type: String },
	joinToCreate: { type: String },
	logChannel: { type: String },
	leaveChannel: { type: String },
	level: { type: Boolean, default: true },
	log: { type: Boolean, default: false },
	welcome: { type: Boolean, default: false },
	leave: { type: Boolean, default: false },
	memberup: { type: Boolean, default: false },
	banremove: { type: Boolean, default: false },
	cCreate: { type: Boolean, default: false },
	cDelete: { type: Boolean, default: false },
	cpinsUp: { type: Boolean, default: false },
	cUp: { type: Boolean, default: false },
	eCreate: { type: Boolean, default: false },
	eDelete: { type: Boolean, default: false },
	eUpdate: { type: Boolean, default: false },
	rCreate: { type: Boolean, default: false },
	banadd: { type: Boolean, default: false },
	rDelete: { type: Boolean, default: false },
	rUpdate: { type: Boolean, default: false },
	xp: { type: String, default: 50 },
	chatbot: { type: Boolean, default: false },
	chatbotChannel: { type: String },
	chatbotlang: { type: String, default: 'vn' },
});
module.exports = new mongoose.model('Guild', guildSchema, 'guilds');
